DEVREL-885 Stack rewrite
kontent-ai-bot/kontent-ai-new-sample-app pull request #20
Opened 2023-06-20 14:18 UTC by Simply007

### Motivation

DEVREL-885

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

2023-06-22 08:45 UTC, IvanKiral commented
if we add m-0 in classname in Image in GenericAction.tsx, the image would not have this not really nice padding on top

2023-06-22 08:47 UTC, IvanKiral requested changes

2023-06-26 08:33 UTC, Simply007 commented on components/shared/Stack.tsx
> +  const siteCodename = useSiteCodename();
Fixed: 6b266c3

2023-06-26 08:36 UTC, Simply007 commented
> if we add m-0 in classname in Image in GenericAction.tsx, the image would not have this not really nice padding on top

OK done in 4759fe8

2023-06-26 09:00 UTC, IvanKiral approved these changes

2023-06-26 09:02 UTC, merged